
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReceiveGPSInfo", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://qintegrator.qs3.com.mx/ReceiveGPSInformation/ReceiveGPSInfo.asmx?wsdl")
public class ReceiveGPSInfo
    extends Service
{

    private final static URL RECEIVEGPSINFO_WSDL_LOCATION;
    private final static WebServiceException RECEIVEGPSINFO_EXCEPTION;
    private final static QName RECEIVEGPSINFO_QNAME = new QName("http://tempuri.org/", "ReceiveGPSInfo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://qintegrator.qs3.com.mx/ReceiveGPSInformation/ReceiveGPSInfo.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEIVEGPSINFO_WSDL_LOCATION = url;
        RECEIVEGPSINFO_EXCEPTION = e;
    }

    public ReceiveGPSInfo() {
        super(__getWsdlLocation(), RECEIVEGPSINFO_QNAME);
    }

    public ReceiveGPSInfo(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEIVEGPSINFO_QNAME, features);
    }

    public ReceiveGPSInfo(URL wsdlLocation) {
        super(wsdlLocation, RECEIVEGPSINFO_QNAME);
    }

    public ReceiveGPSInfo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEIVEGPSINFO_QNAME, features);
    }

    public ReceiveGPSInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveGPSInfo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReceiveGPSInfoSoap
     */
    @WebEndpoint(name = "ReceiveGPSInfoSoap")
    public ReceiveGPSInfoSoap getReceiveGPSInfoSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ReceiveGPSInfoSoap"), ReceiveGPSInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveGPSInfoSoap
     */
    @WebEndpoint(name = "ReceiveGPSInfoSoap")
    public ReceiveGPSInfoSoap getReceiveGPSInfoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ReceiveGPSInfoSoap"), ReceiveGPSInfoSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ReceiveGPSInfoSoap
     */
    @WebEndpoint(name = "ReceiveGPSInfoSoap12")
    public ReceiveGPSInfoSoap getReceiveGPSInfoSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ReceiveGPSInfoSoap12"), ReceiveGPSInfoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveGPSInfoSoap
     */
    @WebEndpoint(name = "ReceiveGPSInfoSoap12")
    public ReceiveGPSInfoSoap getReceiveGPSInfoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ReceiveGPSInfoSoap12"), ReceiveGPSInfoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEIVEGPSINFO_EXCEPTION!= null) {
            throw RECEIVEGPSINFO_EXCEPTION;
        }
        return RECEIVEGPSINFO_WSDL_LOCATION;
    }

}
