
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReceiveGPSInfoSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceiveGPSInfoSoap {


    /**
     * 
     * @param xmlGPSInfo
     * @return
     *     returns org.tempuri.ReceiveGPSInformationResponse.ReceiveGPSInformationResult
     */
    @WebMethod(operationName = "ReceiveGPSInformation", action = "http://tempuri.org/ReceiveGPSInformation")
    @WebResult(name = "ReceiveGPSInformationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReceiveGPSInformation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveGPSInformation")
    @ResponseWrapper(localName = "ReceiveGPSInformationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveGPSInformationResponse")
    public org.tempuri.ReceiveGPSInformationResponse.ReceiveGPSInformationResult receiveGPSInformation(
        @WebParam(name = "xmlGPSInfo", targetNamespace = "http://tempuri.org/")
        org.tempuri.ReceiveGPSInformation.XmlGPSInfo xmlGPSInfo);

    /**
     * 
     * @param gpsInformation
     * @return
     *     returns org.tempuri.Protocolo
     */
    @WebMethod(operationName = "ReceiveGPSInformation_Objeto", action = "http://tempuri.org/ReceiveGPSInformation_Objeto")
    @WebResult(name = "ReceiveGPSInformation_ObjetoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReceiveGPSInformation_Objeto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveGPSInformationObjeto")
    @ResponseWrapper(localName = "ReceiveGPSInformation_ObjetoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveGPSInformationObjetoResponse")
    public Protocolo receiveGPSInformationObjeto(
        @WebParam(name = "GPSInformation", targetNamespace = "http://tempuri.org/")
        GPSInfo gpsInformation);

    /**
     * 
     * @param gpsInformation
     * @return
     *     returns org.tempuri.ArrayOfProtocolo
     */
    @WebMethod(operationName = "ReceiveGPSInformation_Objetos", action = "http://tempuri.org/ReceiveGPSInformation_Objetos")
    @WebResult(name = "ReceiveGPSInformation_ObjetosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReceiveGPSInformation_Objetos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveGPSInformationObjetos")
    @ResponseWrapper(localName = "ReceiveGPSInformation_ObjetosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveGPSInformationObjetosResponse")
    public ArrayOfProtocolo receiveGPSInformationObjetos(
        @WebParam(name = "GPSInformation", targetNamespace = "http://tempuri.org/")
        ArrayOfGPSInfo gpsInformation);

    /**
     * 
     * @param xmlGPSInfo
     * @return
     *     returns org.tempuri.ReceiveGPSInformationMassiveXMLResponse.ReceiveGPSInformationMassiveXMLResult
     */
    @WebMethod(operationName = "ReceiveGPSInformationMassiveXML", action = "http://tempuri.org/ReceiveGPSInformationMassiveXML")
    @WebResult(name = "ReceiveGPSInformationMassiveXMLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReceiveGPSInformationMassiveXML", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveGPSInformationMassiveXML")
    @ResponseWrapper(localName = "ReceiveGPSInformationMassiveXMLResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveGPSInformationMassiveXMLResponse")
    public org.tempuri.ReceiveGPSInformationMassiveXMLResponse.ReceiveGPSInformationMassiveXMLResult receiveGPSInformationMassiveXML(
        @WebParam(name = "xmlGPSInfo", targetNamespace = "http://tempuri.org/")
        org.tempuri.ReceiveGPSInformationMassiveXML.XmlGPSInfo xmlGPSInfo);

}
